# Generated by Django 4.2.15 on 2024-08-26 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the color scheme', max_length=100)),
                ('primary', models.CharField(default='#000000', help_text='Primary color in hexadecimal format', max_length=7)),
                ('secondary', models.CharField(default='#000000', help_text='Secondary color in hexadecimal format', max_length=7)),
                ('tertiary', models.CharField(default='#000000', help_text='Tertiary color in hexadecimal format', max_length=7)),
                ('light', models.CharField(default='#FFFFFF', help_text='Light color in hexadecimal format', max_length=7)),
                ('dark', models.CharField(default='#000000', help_text='Dark color in hexadecimal format', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the font', max_length=100)),
                ('url', models.URLField(help_text='URL of the font')),
            ],
        ),
        migrations.CreateModel(
            name='HeroBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Hero background image title', max_length=200)),
                ('image', models.ImageField(help_text='Hero background image', upload_to='hero_background_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Hero image title', max_length=200)),
                ('image', models.ImageField(help_text='Hero image', upload_to='hero_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the template', max_length=100)),
                ('easter_egg', models.BooleanField(default=False, help_text='Indicates if this template is active')),
                ('text_light', models.BooleanField(default=False, help_text='Indicates if the text should be light')),
                ('colors', models.ForeignKey(blank=True, help_text='Color scheme for the template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.colors')),
                ('font', models.ForeignKey(blank=True, help_text='Font for the template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.font')),
                ('hero_background_image', models.ForeignKey(blank=True, help_text='Hero background image for the template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.herobackgroundimage')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Hero image for the template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.heroimage')),
            ],
        ),
    ]
