# Generated by Django 5.1 on 2024-08-13 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the color scheme', max_length=100)),
                ('primary', models.CharField(default='#000000', help_text='Primary color in hexadecimal format', max_length=7)),
                ('secondary', models.CharField(default='#000000', help_text='Secondary color in hexadecimal format', max_length=7)),
                ('tertiary', models.CharField(default='#000000', help_text='Tertiary color in hexadecimal format', max_length=7)),
                ('light', models.CharField(default='#FFFFFF', help_text='Light color in hexadecimal format', max_length=7)),
                ('dark', models.CharField(default='#000000', help_text='Dark color in hexadecimal format', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Hero image title', max_length=200)),
                ('image', models.ImageField(help_text='Hero image', upload_to='hero_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text', max_length=200)),
                ('active', models.BooleanField(default=True, help_text='Is this image active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project', max_length=100)),
                ('description', models.TextField(help_text='Description of the project')),
                ('url', models.URLField(help_text='URL of the project')),
                ('image', models.ImageField(help_text='Image of the project', upload_to='proyectos/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the template', max_length=100)),
                ('html_file', models.FileField(help_text='HTML file for the template', upload_to='templates/')),
                ('active', models.BooleanField(default=True, help_text='Indicates if this template is active')),
                ('colors', models.ForeignKey(blank=True, help_text='Color scheme for the template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.colors')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Hero image for the template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.heroimage')),
            ],
        ),
    ]
