# Generated by Django 4.2.15 on 2024-08-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='body_font',
            field=models.ForeignKey(blank=True, help_text='Body font for the template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_font', to='api.font'),
        ),
    ]
