# Generated by Django 5.1 on 2024-08-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroimage',
            name='active',
        ),
    ]
