# Generated by Django 5.1 on 2024-08-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_heroimage_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='html_file',
        ),
    ]
