# Generated by Django 4.2.15 on 2024-08-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_template_body_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='background_dark',
            field=models.BooleanField(default=False, help_text='Indicates if the background should be dark'),
        ),
    ]
