# Generated by Django 4.2.15 on 2024-08-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_template_background_dark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='background_dark',
        ),
    ]
