# Generated by Django 5.1 on 2024-08-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='active',
            new_name='easter_egg',
        ),
    ]
