# Generated by Django 5.1 on 2024-08-16 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_active_template_easter_egg'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Hero background image title', max_length=200)),
                ('image', models.ImageField(help_text='Hero background image', upload_to='hero_background_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='template',
            name='easter_egg',
            field=models.BooleanField(default=False, help_text='Indicates if this template is active'),
        ),
        migrations.AddField(
            model_name='template',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, help_text='Hero background image for the template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.herobackgroundimage'),
        ),
    ]
