# Generated by Django 5.1 on 2024-08-16 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_herobackgroundimage_alter_template_easter_egg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the font', max_length=100)),
                ('url', models.URLField(help_text='URL of the font')),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='font',
            field=models.ForeignKey(blank=True, help_text='Font for the template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.font'),
        ),
    ]
