# Generated by Django 5.1 on 2024-08-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_font_template_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='text_light',
            field=models.BooleanField(default=False, help_text='Indicates if the text should be light'),
        ),
    ]
