# Generated by Django 4.2.15 on 2024-08-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_dark',
            field=models.BooleanField(default=False),
        ),
    ]
