# Generated by Django 4.2.15 on 2024-08-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_profile_background_dark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Native', 'Native')], default=('Basic', 'Basic'), max_length=20),
            preserve_default=False,
        ),
    ]
