# Generated by Django 4.2.15 on 2024-08-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_alter_language_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
