# Generated by Django 4.2.15 on 2024-08-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_alter_skill_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('html', models.FileField(upload_to='templates')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='htmltemplate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.htmltemplate'),
        ),
    ]
